In [4]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2016.csv" , encoding="latin1" , sep=";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,IBBS_1,HANE_GELIR_AYLIK,HHB,HANE_FAKTOR
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13700 entries, 0 to 13699
Data columns (total 42 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   13700 non-null  int64
 1   BULTEN_NO                      13700 non-null  int64
 2   CEVAPLILIK_DURUM               13700 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           11874 non-null  float64
 4   MEKTUP_BROSUR                  11874 non-null  float64
 5   BT_BILG_MASAUSTU               11276 non-null  float64
 6   BT_BILG_TASINABILIR            11276 non-null  float64
 7   BT_TABLET                      11276 non-null  float64
 8   BT_TEL_CEP                     11276 non-null  float64
 9   BT_OYUNKONSOL                  11276 non-null  float64
 10  BT_TEL_SABIT                   11276 non-null  float64
 11  BT_FOTOGRAF_KAMERA             11276 non-null  float64
 12  BT_DVD_VCD_OYNATICI            11276 non-null  float64
 13  BT_INTBAGLANAN_TV              11276 non-null  float64
 14  BT_DIGER                       11276 non-null  float64
 15  BT_ACIKLAMA                    12 non-null     str
 16  HANE_BILGISAYAR_KULLANIM       11276 non-null  float64
 17  HANE_INTERNET_ERISIM_DURUMU    11276 non-null  float64
 18  HANE_INTERNET_ERISIM_KULLANIM  8081 non-null   float64
 19  INT_BAGLANMA_MASAUSTU          8081 non-null   float64
 20  INT_BAGLANMA_TASINABILIR       8081 non-null   float64
 21  INT_BAGLANMA_TABLET            8081 non-null   float64
 22  INT_BAGLANMA_TEL_CEP           8081 non-null   float64
 23  INT_BAGLANMA_DIGER_CIHAZ       8081 non-null   float64
 24  INT_BAGLANMA_TV                8081 non-null   float64
 25  INT_BAGLANTI_SABIT_GENIS       8081 non-null   float64
 26  INT_BAGLANTI_MOBIL_GENIS       8081 non-null   float64
 27  INT_BAGLANTI_CEVIRMELI_ISDN    8081 non-null   float64
 28  INT_BAGLANTI_TEL_DARBANT       8081 non-null   float64
 29  INT_BAGLANMAMA_BASKAYER        3140 non-null   float64
 30  INT_BAGLANMAMA_GEREKYOK        3140 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_CIHAZ     3140 non-null   float64
 32  INT_BAGLANMAMA_FIYAT_BAGLANTI  3140 non-null   float64
 33  INT_BAGLANMAMA_BILMEME         3140 non-null   float64
 34  INT_BAGLANMAMA_GIZLILIK        3140 non-null   float64
 35  INT_BAGLANMAMA_IMKAN_YOK       3140 non-null   float64
 36  INT_BAGLANMAMA_ENGEL           3140 non-null   float64
 37  INT_BAGLANMAMA_DIGER           3141 non-null   float64
 38  IBBS_1                         13700 non-null  str
 39  HANE_GELIR_AYLIK               11276 non-null  float64
 40  HHB                            11874 non-null  float64
 41  HANE_FAKTOR                    11874 non-null  str
dtypes: float64(36), int64(3), str(3)
memory usage: 4.4 MB

In [10]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILGISAYAR_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TELEFON_SABIT": "hanede sabit telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_OYUNKONSOL": "evde olan oyun konsolunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_ADSL": "internet bağlantı türü adsl"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_UYDU": "internet bağlantı türü kablo tv altyapısı üzerinden kablolu"}, inplace=True)
df.rename(columns={"KABLOLU_SABIT_FIBER": "internet bağlantı türü fiber bağlantı, ethernet, PLC vb"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_KABLOSUZ_SABIT": "internet bağlantı türü kablolu sabit internet "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_3G": "internet bağlantı türü taşınabilir bir cihaz ile (cep telefonu, tablet vb.) 3G bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MODEM_3G": "internet bağlantı türü 3G modemi üzerinden mobil bağlantı (VINN, JET, VODEM vb."}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TELEFON_DARBANT": "internet bağlantı türü cep telefonu üzerinden darbant bağlantı ( WAP, GPRS) "}, inplace=True)
df.rename(columns={"BT_ACIKLAMA": "hanede var olan bilişim cihazları açıklaması"}, inplace=True)

In [11]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"

In [12]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2016temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2016temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hanede var olan bilişim cihazları açıklaması,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,istatistiki bölge birimleri sınıflaması (düzey 1),hane gelir aylık,hane büyüklüğü,hane ağırlık katsayısı
0,2016,10011,1,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,4.0,"1129,923989"
1,2016,10012,1,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,1500.0,4.0,"1567,389768"
2,2016,10013,1,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,TR1,1000.0,1.0,"2775,012572"
3,2016,10014,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,2000.0,5.0,"2757,222088"
4,2016,10015,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,900.0,1.0,"2530,296443"