In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2017.csv", sep = ";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,...,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15490 entries, 0 to 15489
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   15490 non-null  int64
 1   BULTEN_NO                      15490 non-null  int64
 2   CEVAPLILIK_DURUM               15490 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           13487 non-null  float64
 4   MEKTUP_BROSUR                  13487 non-null  float64
 5   BT_BILG_MASAUSTU               12781 non-null  float64
 6   BT_BILG_TASINABILIR            12781 non-null  float64
 7   BT_TABLET                      12781 non-null  float64
 8   BT_TEL_CEP                     12781 non-null  float64
 9   BT_OYUNKONSOL                  12781 non-null  float64
 10  BT_TEL_SABIT                   12781 non-null  float64
 11  BT_FOTOGRAF_KAMERA             12781 non-null  float64
 12  BT_DVD_VCD_OYNATICI            12781 non-null  float64
 13  BT_INTBAGLANAN_TV              12781 non-null  float64
 14  BT_DIGER                       12781 non-null  float64
 15  HANE_BILGISAYAR_KULLANIM       12781 non-null  float64
 16  HANE_INTERNET_ERISIM_DURUMU    12781 non-null  float64
 17  HANE_INTERNET_ERISIM_KULLANIM  9888 non-null   float64
 18  INT_BAGLANMA_MASAUSTU          9888 non-null   float64
 19  INT_BAGLANMA_TASINABILIR       9888 non-null   float64
 20  INT_BAGLANMA_TABLET            9888 non-null   float64
 21  INT_BAGLANMA_TEL_CEP           9888 non-null   float64
 22  INT_BAGLANMA_DIGER_CIHAZ       9888 non-null   float64
 23  INT_BAGLANMA_TV                9888 non-null   float64
 24  INT_BAGLANTI_SABIT_GENIS       9888 non-null   float64
 25  INT_BAGLANTI_MOBIL_GENIS       9888 non-null   float64
 26  INT_BAGLANTI_CEVIRMELI_ISDN    9888 non-null   float64
 27  INT_BAGLANTI_TEL_DARBANT       9888 non-null   float64
 28  INT_BAGLANMAMA_BASKAYER        2865 non-null   float64
 29  INT_BAGLANMAMA_GEREKYOK        2865 non-null   float64
 30  INT_BAGLANMAMA_FIYAT_CIHAZ     2865 non-null   float64
 31  INT_BAGLANMAMA_FIYAT_BAGLANTI  2865 non-null   float64
 32  INT_BAGLANMAMA_BILMEME         2865 non-null   float64
 33  INT_BAGLANMAMA_GIZLILIK        2865 non-null   float64
 34  INT_BAGLANMAMA_IMKAN_YOK       2865 non-null   float64
 35  INT_BAGLANMAMA_ENGEL           2865 non-null   float64
 36  INT_BAGLANMAMA_DIGER           2865 non-null   float64
 37  HHB                            13487 non-null  float64
 38  HANE_GELIR_AYLIK               12781 non-null  float64
 39  IBBS_1                         15490 non-null  str
 40  HANE_FAKTOR                    13487 non-null  str
dtypes: float64(36), int64(3), str(2)
memory usage: 4.8 MB

In [4]:
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,MEKTUP_BROSUR,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_TEL_SABIT,BT_FOTOGRAF_KAMERA,BT_DVD_VCD_OYNATICI,BT_INTBAGLANAN_TV,BT_DIGER,HANE_BILGISAYAR_KULLANIM,HANE_INTERNET_ERISIM_DURUMU,HANE_INTERNET_ERISIM_KULLANIM,INT_BAGLANMA_MASAUSTU,INT_BAGLANMA_TASINABILIR,INT_BAGLANMA_TABLET,INT_BAGLANMA_TEL_CEP,INT_BAGLANMA_DIGER_CIHAZ,INT_BAGLANMA_TV,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,INT_BAGLANMAMA_BASKAYER,INT_BAGLANMAMA_GEREKYOK,INT_BAGLANMAMA_FIYAT_CIHAZ,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HHB,HANE_GELIR_AYLIK,IBBS_1,HANE_FAKTOR
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"

In [5]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)

In [10]:
df.rename(columns={"MEKTUP_BROSUR": "hane bilgilendirme mektubunun ulaşma durumu"}, inplace=True)
df.rename(columns={"BT_TEL_SABIT": "hanede sabit hatlı telefon var mı"}, inplace=True)
df.rename(columns={"BT_FOTOGRAF_KAMERA": "hanede dijital fotoğraf makinesi var mı"}, inplace=True)
df.rename(columns={"BT_DVD_VCD_OYNATICI": "hanede dvd/vcd oynatıcı var mı"}, inplace=True)
df.rename(columns={"BT_DIGER": "hanede diğer olan bilişim ekipmanları"}, inplace=True)
df.rename(columns={"HANE_BILGISAYAR_KULLANIM": "hane bilgisayar kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "evde olan masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "evde olan dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "evde olan tabletin internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "evde olan cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "evde olan diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "evde olan tv internete bağlanma durumu"}, inplace=True)

In [11]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15485,2017,254510,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1400.0,TRC,"1354,453276"
15486,2017,254610,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,1000.0,TRC,"2112,420995"
15487,2017,254710,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,5.0,1400.0,TRC,"1948,374117"
15488,2017,254810,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,1400.0,TRC,"2817,960304"
15489,2017,254910,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,8.0,300.0,TRC,"2953,635066"

In [12]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2017temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hane bilgilendirme mektubunun ulaşma durumu,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede sabit hatlı telefon var mı,hanede dijital fotoğraf makinesi var mı,hanede dvd/vcd oynatıcı var mı,hanede akıllı tv var mı,hanede diğer olan bilişim ekipmanları,hane bilgisayar kullanım durumu,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,evde olan masaüstü bilgisayarın internete bağlanma durumu,evde olan dizüstü bilgisayarın internete bağlanma durumu,evde olan tabletin internete bağlanma durumu,evde olan cep telefonunun internete bağlanma durumu,evde olan diğer cihazların internete bağlanma durumu,evde olan tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane büyüklüğü,hane gelir aylık,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2017,10011,1,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5000.0,TR1,"2527,94537"
1,2017,10012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TR1,NaN
2,2017,10013,1,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2000.0,TR1,"2169,012791"
3,2017,10014,1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5000.0,TR1,"3158,223133"
4,2017,10015,1,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1250.0,TR1,"1844,225692"