In [1]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2018.csv", sep = ";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_INTBAGLANAN_TV,...,INT_BAGLANMA_DIGER_CIHAZ,INT_BAGLANMA_TV,INT_BAGLANTI_SABIT_GENIS,INT_BAGLANTI_MOBIL_GENIS,INT_BAGLANTI_CEVIRMELI_ISDN,INT_BAGLANTI_TEL_DARBANT,HANE_GELIR_AYLIK,HHB,IBBS_1,hanefaktor
0,2018,18852,1,1,2.0,1.0,1.0,1.0,2.0,2.0,...,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,4,TR8,"1283,806022"
1,2018,233310,1,1,2.0,1.0,1.0,1.0,2.0,2.0,...,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,2,TR2,"1257,256238"
2,2018,145810,1,1,2.0,2.0,1.0,1.0,2.0,1.0,...,2.0,1.0,1.0,1.0,2.0,2.0,2500.0,4,TR4,"2504,539322"
3,2018,12902,1,1,2.0,1.0,2.0,1.0,2.0,2.0,...,2.0,2.0,1.0,1.0,2.0,2.0,1500.0,2,TR3,"2810,576636"
4,2018,18871,1,1,2.0,2.0,2.0,1.0,2.0,2.0,...,2.0,2.0,2.0,1.0,2.0,2.0,1400.0,1,TR8,"1595,311609"

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13427 entries, 0 to 13426
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   REFERANS_YIL                   13427 non-null  int64
 1   BULTEN_NO                      13427 non-null  int64
 2   CEVAPLILIK_DURUM               13427 non-null  int64
 3   KAPSAMICI_KAPSAMDISI           13427 non-null  int64
 4   BT_BILG_MASAUSTU               12828 non-null  float64
 5   BT_BILG_TASINABILIR            12828 non-null  float64
 6   BT_TABLET                      12828 non-null  float64
 7   BT_TEL_CEP                     12828 non-null  float64
 8   BT_OYUNKONSOL                  12828 non-null  float64
 9   BT_INTBAGLANAN_TV              12828 non-null  float64
 10  HANE_INTERNET_ERISIM_DURUMU    12828 non-null  float64
 11  HANE_INTERNET_ERISIM_KULLANIM  10318 non-null  float64
 12  INT_BAGLANMA_MASAUSTU          10318 non-null  float64
 13  INT_BAGLANMA_TASINABILIR       10318 non-null  float64
 14  INT_BAGLANMA_TABLET            10318 non-null  float64
 15  INT_BAGLANMA_TEL_CEP           10318 non-null  float64
 16  INT_BAGLANMA_DIGER_CIHAZ       10318 non-null  float64
 17  INT_BAGLANMA_TV                10318 non-null  float64
 18  INT_BAGLANTI_SABIT_GENIS       10318 non-null  float64
 19  INT_BAGLANTI_MOBIL_GENIS       10318 non-null  float64
 20  INT_BAGLANTI_CEVIRMELI_ISDN    10318 non-null  float64
 21  INT_BAGLANTI_TEL_DARBANT       10320 non-null  float64
 22  HANE_GELIR_AYLIK               12828 non-null  float64
 23  HHB                            13427 non-null  int64
 24  IBBS_1                         13427 non-null  str
 25  hanefaktor                     13427 non-null  str
dtypes: float64(19), int64(5), str(2)
memory usage: 2.7 MB

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)

In [6]:
df.rename(columns={"INT_BAGLANMA_MASAUSTU": "masaüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TASINABILIR": "dizüstü bilgisayarın internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TABLET": "tablerin internete bağlanma durumı"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TEL_CEP": "cep telefonunun internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_DIGER_CIHAZ": "diğer cihazların internete bağlanma durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANMA_TV": "tv internete bağlanma durumu"}, inplace=True)

In [7]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanefaktor
0,2018,18852,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,4,TR8,"1283,806022"
1,2018,233310,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,2,TR2,"1257,256238"
2,2018,145810,1,1,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2500.0,4,TR4,"2504,539322"
3,2018,12902,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1500.0,2,TR3,"2810,576636"
4,2018,18871,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1400.0,1,TR8,"1595,311609"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13422,2018,13957,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,5000.0,4,TR4,"1668,12873"
13423,2018,14222,1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2250.0,4,TR4,"1916,640147"
13424,2018,11731,1,1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,5000.0,4,TR1,"2945,125505"
13425,2018,10638,1,1,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,3800.0,4,TR1,"2935,654851"
13426,2018,11621,1,1,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1860.0,2,TR1,"1012,645121"

In [8]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2018temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2018temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,masaüstü bilgisayarın internete bağlanma durumu,dizüstü bilgisayarın internete bağlanma durumu,tablerin internete bağlanma durumı,cep telefonunun internete bağlanma durumu,diğer cihazların internete bağlanma durumu,tv internete bağlanma durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hanefaktor
0,2018,18852,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,4,TR8,"1283,806022"
1,2018,233310,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,3000.0,2,TR2,"1257,256238"
2,2018,145810,1,1,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2500.0,4,TR4,"2504,539322"
3,2018,12902,1,1,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1500.0,2,TR3,"2810,576636"
4,2018,18871,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1400.0,1,TR8,"1595,311609"