In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane_2019.csv", sep = ";" )
df.head()

,REFERANS_YIL,BULTEN_NO,CEVAPLILIK_DURUM,KAPSAMICI_KAPSAMDISI,BT_BILG_MASAUSTU,BT_BILG_TASINABILIR,BT_TABLET,BT_TEL_CEP,BT_OYUNKONSOL,BT_INTBAGLANAN_TV,...,INT_BAGLANMAMA_FIYAT_BAGLANTI,INT_BAGLANMAMA_BILMEME,INT_BAGLANMAMA_GIZLILIK,INT_BAGLANMAMA_IMKAN_YOK,INT_BAGLANMAMA_ENGEL,INT_BAGLANMAMA_DIGER,HANE_GELIR_AYLIK,HHB,IBBS_1,HANE_FAKTOR
0,2019,10011,1,1,2.0,2.0,2.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3800.0,2,TR1,"2210,281659"
1,2019,100110,1,1,2.0,1.0,1.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1500.0,3,TR1,"993,6368057"
2,2019,10012,1,1,2.0,1.0,1.0,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,5,TR1,"5184,202989"
3,2019,10013,1,1,2.0,1.0,1.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,4,TR1,"1566,954808"
4,2019,10014,1,1,2.0,2.0,2.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1600.0,3,TR1,"2909,815207"

In [9]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13561 entries, 0 to 13560
Data columns (total 29 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   referans yıl                                              13561 non-null  int64
 1   bülten no                                                 13561 non-null  int64
 2   cevaplılık durum                                          13561 non-null  int64
 3   kapsam içi/dışı                                           13561 non-null  int64
 4   hanede masaüstü bilgisayar var mı                         12955 non-null  float64
 5   hanede dizüstü bilgisayar var mı                          12956 non-null  float64
 6   hanede tablet var mı                                      12956 non-null  float64
 7   hanede cep telefonu var mı                                12956 non-null  float64
 8   hanede oyun konsolu var mı                                12956 non-null  float64
 9   hanede akıllı tv var mı                                   12956 non-null  float64
 10  hane internet erişim durumu                               12956 non-null  float64
 11  internet erişimi olan hanelerin internet kullanım durumu  11127 non-null  float64
 12  sabit internet (ev interneti)                             11127 non-null  float64
 13  mobil internet                                            11127 non-null  float64
 14  internet bağlantı türü çevirmeli bağlantı veya ısdn       11127 non-null  float64
 15  cep telefonu üzerinden darbant bağlantı                   11127 non-null  float64
 16  INT_BAGLANMAMA_BASKAYER                                   1816 non-null   float64
 17  INT_BAGLANMAMA_GEREKYOK                                   1816 non-null   float64
 18  INT_BAGLANMAMA_FIYAT_CIHAZ                                1816 non-null   float64
 19  INT_BAGLANMAMA_FIYAT_BAGLANTI                             1816 non-null   float64
 20  INT_BAGLANMAMA_BILMEME                                    1816 non-null   float64
 21  INT_BAGLANMAMA_GIZLILIK                                   1816 non-null   float64
 22  INT_BAGLANMAMA_IMKAN_YOK                                  1816 non-null   float64
 23  INT_BAGLANMAMA_ENGEL                                      1816 non-null   float64
 24  INT_BAGLANMAMA_DIGER                                      1816 non-null   float64
 25  hane gelir aylık                                          13065 non-null  float64
 26  hane büyüklüğü                                            13561 non-null  int64
 27  istatistiki bölge birimleri sınıflaması (düzey 1)         13561 non-null  str
 28  hane ağırlık katsayısı                                    13561 non-null  str
dtypes: float64(22), int64(5), str(2)
memory usage: 3.0 MB

In [11]:
df.columns

Index(['referans yıl', 'bülten no', 'cevaplılık durum', 'kapsam içi/dışı',
       'hanede masaüstü bilgisayar var mı', 'hanede dizüstü bilgisayar var mı',
       'hanede tablet var mı', 'hanede cep telefonu var mı',
       'hanede oyun konsolu var mı', 'hanede akıllı tv var mı',
       'hane internet erişim durumu',
       'internet erişimi olan hanelerin internet kullanım durumu',
       'sabit internet (ev interneti)', 'mobil internet',
       'internet bağlantı türü çevirmeli bağlantı veya ısdn ',
       'cep telefonu üzerinden darbant bağlantı', 'INT_BAGLANMAMA_BASKAYER',
       'INT_BAGLANMAMA_GEREKYOK', 'INT_BAGLANMAMA_FIYAT_CIHAZ',
       'INT_BAGLANMAMA_FIYAT_BAGLANTI', 'INT_BAGLANMAMA_BILMEME',
       'INT_BAGLANMAMA_GIZLILIK', 'INT_BAGLANMAMA_IMKAN_YOK',
       'INT_BAGLANMAMA_ENGEL', 'INT_BAGLANMAMA_DIGER', 'hane gelir aylık',
       'hane büyüklüğü', 'istatistiki bölge birimleri sınıflaması (düzey 1)',
       'hane ağırlık katsayısı'],
      dtype='str')

In [12]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_20": "hanenin aylık toplam net geliri (20'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_TEL_CEP": "hanede cep telefonu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)
df.rename(columns={"KAPSAMICI_KAPSAMDISI": "kapsam içi/dışı"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_SABIT_GENIS": "sabit internet (ev interneti)"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_MOBIL_GENIS": "mobil internet"}, inplace=True)
df.rename(columns={"HANE_GELIR_AYLIK": "hane gelir aylık"}, inplace=True)
df.rename(columns={"CEVAPLILIK_DURUM": "cevaplılık durum"}, inplace=True)
df.rename(columns={"BT_BILG_TASINABILIR": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_INTBAGLANAN_TV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_KULLANIM": "internet erişimi olan hanelerin internet kullanım durumu"}, inplace=True)
df.rename(columns={"INT_BAGLANTI_CEVIRMELI_ISDN": "internet bağlantı türü çevirmeli bağlantı veya ısdn "}, inplace=True)
df.rename(columns={"INT_BAGLANTI_TEL_DARBANT": "cep telefonu üzerinden darbant bağlantı"}, inplace=True)

In [15]:
df.rename(columns={"INT_BAGLANMAMA_BASKAYER": "evden internete bağlanmıyor başka yerden bağlanıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GEREKYOK": "haneden kimsenin internete bağlanmasına gerek yok"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_CIHAZ": "bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_FIYAT_BAGLANTI": "internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_BILMEME": "internete bağlanmayı bilmediği için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_GIZLILIK": "gizlilik/güvenlik endişesi ile evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_IMKAN_YOK": "bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_ENGEL": "kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor"}, inplace=True)
df.rename(columns={"INT_BAGLANMAMA_DIGER": "evden internete bağlanmama diğer"}, inplace=True)

In [16]:
df

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2019,10011,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3800.0,2,TR1,"2210,281659"
1,2019,100110,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.0,3,TR1,"993,6368057"
2,2019,10012,1,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,5,TR1,"5184,202989"
3,2019,10013,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,4,TR1,"1566,954808"
4,2019,10014,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1600.0,3,TR1,"2909,815207"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13556,2019,26014,1,1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,400.0,2,TRC,"783,3092726"
13557,2019,26015,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,8,TRC,"1577,401115"
13558,2019,26016,1,1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,800.0,3,TRC,"570,194474"
13559,2019,26017,1,1,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2020.0,10,TRC,"2002,649375"
13560,2019,26019,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,7,TRC,"2642,685044"

In [17]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2019temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2019temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,cevaplılık durum,kapsam içi/dışı,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,hanede cep telefonu var mı,hanede oyun konsolu var mı,hanede akıllı tv var mı,hane internet erişim durumu,internet erişimi olan hanelerin internet kullanım durumu,sabit internet (ev interneti),mobil internet,internet bağlantı türü çevirmeli bağlantı veya ısdn,cep telefonu üzerinden darbant bağlantı,evden internete bağlanmıyor başka yerden bağlanıyor,haneden kimsenin internete bağlanmasına gerek yok,bilgisayar/modem fiyatları yüksek olduğu için evden internete bağlanmıyor,internete bağlantı ücreti yüksek olduğu için evden internete bağlanmıyor,internete bağlanmayı bilmediği için evden internete bağlanmıyor,gizlilik/güvenlik endişesi ile evden internete bağlanmıyor,bulunan bölgede genişbant bağlantı imkanı olmadığı için evden internete bağlanmıyor,kullanmak için fiziksel engeli bulunduğu için evden internete bağlanmıyor,evden internete bağlanmama diğer,hane gelir aylık,hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2019,10011,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3800.0,2,TR1,"2210,281659"
1,2019,100110,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.0,3,TR1,"993,6368057"
2,2019,10012,1,1,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,5,TR1,"5184,202989"
3,2019,10013,1,1,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,4,TR1,"1566,954808"
4,2019,10014,1,1,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1600.0,3,TR1,"2909,815207"