In [1]:
import pandas as pd 
df= pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2024_hh.xlsx")
df.head()

,REFERANS_YIL,BULTEN_NO,BT_BILG_MASAUSTU,BT_BILG_DIZUSTU,BT_TABLET,BT_TEL_CEP,BT_AKILLITV,BT_AKILLISAAT,BT_OYUNKONSOL,BT_DIGER_CIHAZ,HANE_INTERNET_ERISIM_DURUMU,hane_aylik_gelir_grp_5,HHB,IBBS_1,HANE_FAKTOR
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12159 entries, 0 to 12158
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REFERANS_YIL                 12159 non-null  int64
 1   BULTEN_NO                    12159 non-null  int64
 2   BT_BILG_MASAUSTU             12159 non-null  int64
 3   BT_BILG_DIZUSTU              12159 non-null  int64
 4   BT_TABLET                    12159 non-null  int64
 5   BT_TEL_CEP                   12159 non-null  int64
 6   BT_AKILLITV                  12159 non-null  int64
 7   BT_AKILLISAAT                12159 non-null  int64
 8   BT_OYUNKONSOL                12159 non-null  int64
 9   BT_DIGER_CIHAZ               12159 non-null  int64
 10  HANE_INTERNET_ERISIM_DURUMU  12159 non-null  int64
 11  hane_aylik_gelir_grp_5       12159 non-null  int64
 12  HHB                          12159 non-null  int64
 13  IBBS_1                       12159 non-null  str
 14  HANE_FAKTOR                  12159 non-null  float64
dtypes: float64(1), int64(13), str(1)
memory usage: 1.4 MB

In [4]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)
df.rename(columns={"BT_BILG_MASAUSTU": "hanede masaüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_BILG_DIZUSTU": "hanede dizüstü bilgisayar var mı"}, inplace=True)
df.rename(columns={"BT_TABLET": "hanede tablet var mı"}, inplace=True)
df.rename(columns={"HANE_INTERNET_ERISIM_DURUMU": "hane internet erişim durumu"}, inplace=True)
df.rename(columns={"hane_aylik_gelir_grp_5": "hanenin aylık toplam net geliri (5'li gelir grubu)"}, inplace=True)
df.rename(columns={"HHB": "hane büyüklüğü"}, inplace=True)
df.rename(columns={"IBBS_1": "istatistiki bölge birimleri sınıflaması (düzey 1)"}, inplace=True)
df.rename(columns={"MAH_DEG_L1": "hanehalkı adresinin kır veya kent olma durumu"}, inplace=True)
df.rename(columns={"HANE_FAKTOR": "hane ağırlık katsayısı"}, inplace=True)
df.rename(columns={"BT_AKILLITV": "hanede akıllı tv var mı"}, inplace=True)
df.rename(columns={"BT_AKILLISAAT": "hanede akıllı saat var mı"}, inplace=True)
df.rename(columns={"BT_OYUNKONSOL": "hanede oyun konsolu var mı"}, inplace=True)
df.rename(columns={"BT_DIGER_CIHAZ": "hanede diğer cihazlar var mı"}, inplace=True)

In [5]:
df.to_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv", index=False)
aa = pd.read_csv(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hane bilişim temiz veriler\2024temizhanebilişim.csv")
aa.head()

,referans yıl,bülten no,hanede masaüstü bilgisayar var mı,hanede dizüstü bilgisayar var mı,hanede tablet var mı,BT_TEL_CEP,hanede akıllı tv var mı,hanede akıllı saat var mı,hanede oyun konsolu var mı,hanede diğer cihazlar var mı,hane internet erişim durumu,hanenin aylık toplam net geliri (5'li gelir grubu),hane büyüklüğü,istatistiki bölge birimleri sınıflaması (düzey 1),hane ağırlık katsayısı
0,2024,10011,2,1,2,1,1,2,1,1,1,5,1,TR1,3853.130313
1,2024,10012,2,1,2,1,1,1,2,1,1,5,2,TR1,4555.431051
2,2024,10013,2,1,1,1,1,1,1,1,1,3,2,TR1,4061.128983
3,2024,10014,2,1,1,1,1,2,2,2,1,4,1,TR1,4070.094139
4,2024,10015,1,2,1,1,1,2,2,1,1,5,2,TR1,3076.833933