In [2]:
import pandas as pd

df = pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2025_fert.xlsx")

df.head()

,BULTEN_NO,REFERANS_YIL,GORUSME_YONTEM_FERT,CINSIYET,YAS,HHSORUMLU_YAKINLIK,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,CALISMAMA_NEDEN,...,INT_KBILGI_KORU_IZINVRMEME,INT_KBILGI_KORU_WEBKNTRL,INT_KBILGI_KORU_WEB_TALP,INT_KBILGI_CEREZ_SNR,INT_KBILGI_RKLM_ENDS,INT_KBILGI_ETKNLIK_SNR,INT_HESAP_AC,INT_HESAP_SIL,INT_HESAP_SIL_SORUN,fert_faktor
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274

In [3]:
df = pd.DataFrame(df)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25493 entries, 0 to 25492
Columns: 157 entries, BULTEN_NO to fert_faktor
dtypes: float64(143), int64(12), str(2)
memory usage: 30.5 MB

In [5]:
df["BULTEN_NO"].value_counts()

BULTEN_NO
18336     10
20863      8
23969      8
10938      7
13105      7
          ..
236010     1
237310     1
238510     1
240610     1
240810     1
Name: count, Length: 11924, dtype: int64

In [6]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [7]:
df["REFERANS_YIL"].value_counts()

REFERANS_YIL
2025    25493
Name: count, dtype: int64

In [8]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [9]:
df.head()

,bülten no,referans yıl,GORUSME_YONTEM_FERT,CINSIYET,YAS,HHSORUMLU_YAKINLIK,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,CALISMAMA_NEDEN,...,INT_KBILGI_KORU_IZINVRMEME,INT_KBILGI_KORU_WEBKNTRL,INT_KBILGI_KORU_WEB_TALP,INT_KBILGI_CEREZ_SNR,INT_KBILGI_RKLM_ENDS,INT_KBILGI_ETKNLIK_SNR,INT_HESAP_AC,INT_HESAP_SIL,INT_HESAP_SIL_SORUN,fert_faktor
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274

In [10]:
df["GORUSME_YONTEM_FERT"].value_counts()

GORUSME_YONTEM_FERT
3    18385
1     7108
Name: count, dtype: int64

In [12]:
df.rename(columns={"GORUSME_YONTEM_FERT": "fert no"}, inplace=True)

In [14]:
df.rename(columns={"CINSIYET": "cinsiyet"}, inplace=True)

In [18]:
df.rename(columns={"YAS": "yaş"}, inplace=True)

In [19]:
df.rename(columns={"HHSORUMLU_YAKINLIK": "yakınlık durumu"}, inplace=True)

In [22]:
df.rename(columns={"OKUL_BITEN": "eğitim"}, inplace=True)

In [24]:
df.rename(columns={"OKUMA_YAZMA": "okuma yazma durumu"}, inplace=True)

In [33]:
df.rename(columns={"CALISMA_DURUM": "çalışma durumu"}, inplace=True)

In [35]:
df.rename(columns={"CALISMAMA_NEDEN": "çalışmama nedeni"}, inplace=True)

In [37]:
df.rename(columns={"ISTEKI_DURUM": "işteki durumu"}, inplace=True)

In [45]:
df.rename(columns={"ISCO08": "uluslararası meslek"}, inplace=True)

In [47]:
df.rename(columns={"DOGUM_YER": "doğduğu ülke"}, inplace=True)

In [48]:
df.rename(columns={"DOGUM_YER_ULKE_KOD": "doğduğu ülke kodu"}, inplace=True)

In [50]:
df.rename(columns={"UYRUK": "uyruk"}, inplace=True)

In [52]:
df.rename(columns={"UYRUK_ULKE_KOD": "uyruk ülke kodu"}, inplace=True)

In [53]:
df.rename(columns={"KULLANIM_CEP": "cep telefonu kullanımı"}, inplace=True)

In [55]:
df.rename(columns={"CEP_SAHIP": "cep telefonuna sahip"}, inplace=True)

In [57]:
df.rename(columns={"SON_KULLANIM_INTERNET": "en son internet ne zaman kullanıldı"}, inplace=True)

In [60]:
df.rename(columns={"KULLANIM_SIKLIK_INTERNET": "internet kullanım sıklığı"}, inplace=True)

In [64]:
df.rename(columns={"FERT_INT_MASAUSTU": "masaüstü kullanımı"}, inplace=True)

In [65]:
df.rename(columns={"FERT_INT_DIZUSTU": "dizüstü kullanımı"}, inplace=True)

In [66]:
df.rename(columns={"FERT_INT_TABLET": "tablet kullanımı"}, inplace=True)

In [68]:
df.rename(columns={"FERT_INT_TEL_CEP": "cep telefonu kullanımı"}, inplace=True)

In [70]:
df.rename(columns={"FERT_INT_DGR_CIHAZ": "diğer cihaz kullanımı"}, inplace=True)

In [77]:
df.rename(columns={"INT_FAAL_EPOSTA": "eposta kullanımı"}, inplace=True)

In [79]:
df.rename(columns={"INT_FAAL_TELEFON": "internet araması"}, inplace=True)

In [81]:
df.rename(columns={"INT_FAAL_SOSYAL_GRKATILIM": "sosyal medya kullanımı"}, inplace=True)

In [85]:
df.rename(columns={"INT_FAAL_MESAJ": "sosyal medyada mesajlaşma"}, inplace=True)

In [87]:
df.rename(columns={"INT_FAAL_ONLINE_HABER": "online haber okuma"}, inplace=True)

In [88]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM": "sağlık bilgisi arama"}, inplace=True)

In [89]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM_F": "fiziksel sağlık bilgisi arama"}, inplace=True)

In [90]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM_R": "ruhsal sağlık bilgisi arama"}, inplace=True)

In [91]:
df.rename(columns={"INT_FAAL_MALHIZ_BILGI": "ürün hizmet arama"}, inplace=True)

In [92]:
df.rename(columns={"INT_FAAL_MALHIZ_BILGI_GVNLK": "ürün güvenliği hakkında arama"}, inplace=True)

In [93]:
df.rename(columns={"INT_FAAL_WEBSITE_PAYLASIM": "websitesinde içerik paylaşma"}, inplace=True)

In [96]:
df.rename(columns={"INT_FAAL_OYL_KTLM": "internetten oy katılım"}, inplace=True)

In [98]:
df.rename(columns={"INT_FAAL_ISARAMA": "internetten iş arama"}, inplace=True)

In [101]:
df.rename(columns={"INT_FAAL_MALHIZMET_SATIS": ""}, inplace=True)

In [99]:
df.rename(columns={"INT_FAAL_BANKA_ISLEM": "internetten satış"}, inplace=True)

In [105]:
df.rename(columns={"YAPAYZEKA_KULLAN": "yapay zeka kullanımı"}, inplace=True)

In [107]:
df.rename(columns={"YAPAYZEKA_AMAC_OZEL": "yapay zeka özel amaç kullanımı"}, inplace=True)

In [109]:
df.rename(columns={"YAPAYZEKA_AMAC_IS": "yapay zeka iş için kullanımı"}, inplace=True)

In [111]:
df.rename(columns={"YAPAYZEKA_AMAC_EGT_FRML": "yapay zeka eğitim için kullanımı"}, inplace=True)

In [113]:
df.rename(columns={"YAPAYZEKA_KULLANMAMA_NEDEN": "yapay zeka kullanmama nedeni"}, inplace=True)

In [115]:
df.rename(columns={"INT_FAAL_EGT_KURS": "online kurs"}, inplace=True)

In [117]:
df.rename(columns={"INT_FAAL_EGT_OGRN_MTRYL": "online eğitim materyal"}, inplace=True)

In [119]:
df.rename(columns={"INT_FAAL_EGT_WEB": "online eğitim iletişim"}, inplace=True)

In [121]:
df.rename(columns={"KULLAN_WHATSAPP": "whatsapp kullanımı"}, inplace=True)

In [123]:
df.rename(columns={"KULLAN_INSTAGRAM": "instagram kullanımı"}, inplace=True)

In [126]:
df.rename(columns={"KULLAN_YOUTUBE": "youtube kullanımı"}, inplace=True)

In [127]:
df.rename(columns={"KULLAN_FACEBOOK": "facebook kullanımı"}, inplace=True)

In [128]:
df.rename(columns={"KULLAN_TWITTER": "twitter kullanımı"}, inplace=True)

In [129]:
df.rename(columns={"KULLAN_TELEGRAM": "telegram kullanımı"}, inplace=True)

In [131]:
df.rename(columns={"KULLAN_TIKTOK": "tiktok kullanımı"}, inplace=True)

In [132]:
df.rename(columns={"KULLAN_SNAPCHAT": "snapchat kullanımı"}, inplace=True)

In [134]:
df.rename(columns={"KULLAN_BIP": "bip kullanımı"}, inplace=True)

In [135]:
df.rename(columns={"KULLAN_DIGER": "diğer mobil uygulama kullanımları"}, inplace=True)

In [138]:
df.rename(columns={"EDEVLET_KSL_BILGI_ERISME": "edevlet resmi işlem"}, inplace=True)

In [139]:
df.rename(columns={"EDEVLET_KAMU_BILGI_ERISME": "edevlet kamu bilgi"}, inplace=True)

In [140]:
df.rename(columns={"EDEVLET_BILGI_EDINME": "edevlet hakkında bilgi"}, inplace=True)

In [141]:
df.rename(columns={"EDEVLET_HICBIRI": "edevlette hiçbir sey yapmadı"}, inplace=True)

In [143]:
df.rename(columns={"EDEVLET_FORM_INDIRME": "edevlet form işlemleri"}, inplace=True)

In [144]:
df.rename(columns={"EDEVLET_RANDEVU_REZRVSYN": "edevletten randevu alma"}, inplace=True)

In [145]:
df.rename(columns={"EDEVLET_HESAP_BLG_ALMA": "edevletten bilgi alma"}, inplace=True)

In [146]:
df.rename(columns={"EDEVLET_KSL_VERGI_ONAY": "edevlet vergi işlem"}, inplace=True)

In [147]:
df.rename(columns={"EDEVLET_TALEP_BELGE_SRTFKA": "edevlet belge talep"}, inplace=True)

In [148]:
df.rename(columns={"EDEVLET_TALEP_YARDIM_HAK": "edevlet yardım talep"}, inplace=True)

In [149]:
df.rename(columns={"EDEVLET_TALEP_DIGER": "edevlet diğer talepler"}, inplace=True)

In [151]:
df.rename(columns={"EDEVLET_TALEP_HIC_IHTIYACYOK": "edevletten talepe ihtiyaç yok"}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [ ]:
df.rename(columns={"": ""}, inplace=True)

In [154]:
cols = list(df.columns)
len(cols), cols[69:100], cols[69:100]

(157,
 ['edevletten talepe ihtiyaç yok',
  'EDEVLET_TALEP_HIC_EKSKBILG',
  'EDEVLET_TALEP_HIC_GUVENSIZ',
  'EDEVLET_TALEP_HIC_EKIMLIKYOK',
  'EDEVLET_TALEP_HIC_BASKASI',
  'EDEVLET_TALEP_HIC_DIGER',
  'EDEVLET_SORUN_ZOR',
  'EDEVLET_SORUN_TEKNIK',
  'EDEVLET_SORUN_E_IMZA_KIMLIK',
  'EDEVLET_SORUN_ODEME',
  'EDEVLET_SORUN_MOBIL_ERISIM',
  'EDEVLET_SORUN_DIGER',
  'EDEVLET_SORUN_HIC',
  'EKIMLIK_ERSM_OZEL_AMAC',
  'EKIMLIK_KAMU_HZMT',
  'EKIMLIK_OZEL_HZMT',
  'EKIMLIK_KLLNMM_SBP_HBR_DGL',
  'EKIMLIK_KLLNMM_SBP_YOK',
  'EKIMLIK_KLLNMM_SBP_GRKMD',
  'EKIMLIK_KLLNMM_SBP_GVNSZ',
  'EKIMLIK_KLLNMM_SBP_TKNK_SRN',
  'EKIMLIK_KLLNMM_SBP_AKL_TLF_TBL',
  'EKIMLIK_KLLNMM_SBP_DGR',
  'SON_KULLANIM_ETICARET',
  'ETICARET_FIZIKSEL',
  'WEBSTE_INT_MOBL_ABONE',
  'WEBSTE_ELK_SU_ABONE',
  'WEBSTE_UYGL_ULASIM',
  'WEBSTE_UYGL_RZV_KONAKLAMA',
  'WEBSTE_BILET',
  'WEBSTE_KITAP_E_SESLI'],
 ['edevletten talepe ihtiyaç yok',
  'EDEVLET_TALEP_HIC_EKSKBILG',
  'EDEVLET_TALEP_HIC_GUVENSIZ',
  'EDEVLET_TALEP_HIC_EKIMLIKYOK',
  'EDEVLET_TALEP_HIC_BASKASI',
  'EDEVLET_TALEP_HIC_DIGER',
  'EDEVLET_SORUN_ZOR',
  'EDEVLET_SORUN_TEKNIK',
  'EDEVLET_SORUN_E_IMZA_KIMLIK',
  'EDEVLET_SORUN_ODEME',
  'EDEVLET_SORUN_MOBIL_ERISIM',
  'EDEVLET_SORUN_DIGER',
  'EDEVLET_SORUN_HIC',
  'EKIMLIK_ERSM_OZEL_AMAC',
  'EKIMLIK_KAMU_HZMT',
  'EKIMLIK_OZEL_HZMT',
  'EKIMLIK_KLLNMM_SBP_HBR_DGL',
  'EKIMLIK_KLLNMM_SBP_YOK',
  'EKIMLIK_KLLNMM_SBP_GRKMD',
  'EKIMLIK_KLLNMM_SBP_GVNSZ',
  'EKIMLIK_KLLNMM_SBP_TKNK_SRN',
  'EKIMLIK_KLLNMM_SBP_AKL_TLF_TBL',
  'EKIMLIK_KLLNMM_SBP_DGR',
  'SON_KULLANIM_ETICARET',
  'ETICARET_FIZIKSEL',
  'WEBSTE_INT_MOBL_ABONE',
  'WEBSTE_ELK_SU_ABONE',
  'WEBSTE_UYGL_ULASIM',
  'WEBSTE_UYGL_RZV_KONAKLAMA',
  'WEBSTE_BILET',
  'WEBSTE_KITAP_E_SESLI'])

In [104]:
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,masaüstü kullanım,dizüstü kullanım,tablet kullanımı,cep telefonu kullanımı,diğer cihaz kullanımı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün hizmet arama,ürün güvenliği hakkında arama,websitesinde içerik paylaşma,online oy katılım,internet iş arama,,internetten satış,YAPAYZEKA_KULLAN,YAPAYZEKA_AMAC_OZEL,YAPAYZEKA_AMAC_IS,YAPAYZEKA_AMAC_EGT_FRML,YAPAYZEKA_KULLANMAMA_NEDEN,INT_FAAL_EGT_KURS,INT_FAAL_EGT_OGRN_MTRYL,INT_FAAL_EGT_WEB,KULLAN_WHATSAPP,KULLAN_INSTAGRAM,KULLAN_YOUTUBE,KULLAN_FACEBOOK,KULLAN_TWITTER,KULLAN_TELEGRAM,KULLAN_TIKTOK,KULLAN_SNAPCHAT,KULLAN_BIP,KULLAN_DIGER,EDEVLET_KSL_BILGI_ERISME,EDEVLET_KAMU_BILGI_ERISME,EDEVLET_BILGI_EDINME,EDEVLET_HICBIRI,EDEVLET_FORM_INDIRME,EDEVLET_RANDEVU_REZRVSYN,EDEVLET_HESAP_BLG_ALMA,EDEVLET_KSL_VERGI_ONAY,EDEVLET_TALEP_BELGE_SRTFKA,EDEVLET_TALEP_YARDIM_HAK,EDEVLET_TALEP_DIGER,EDEVLET_TALEP_HIC_IHTIYACYOK,EDEVLET_TALEP_HIC_EKSKBILG,EDEVLET_TALEP_HIC_GUVENSIZ,EDEVLET_TALEP_HIC_EKIMLIKYOK,EDEVLET_TALEP_HIC_BASKASI,EDEVLET_TALEP_HIC_DIGER,EDEVLET_SORUN_ZOR,EDEVLET_SORUN_TEKNIK,EDEVLET_SORUN_E_IMZA_KIMLIK,EDEVLET_SORUN_ODEME,EDEVLET_SORUN_MOBIL_ERISIM,EDEVLET_SORUN_DIGER,EDEVLET_SORUN_HIC,EKIMLIK_ERSM_OZEL_AMAC,EKIMLIK_KAMU_HZMT,EKIMLIK_OZEL_HZMT,EKIMLIK_KLLNMM_SBP_HBR_DGL,EKIMLIK_KLLNMM_SBP_YOK,EKIMLIK_KLLNMM_SBP_GRKMD,EKIMLIK_KLLNMM_SBP_GVNSZ,EKIMLIK_KLLNMM_SBP_TKNK_SRN,EKIMLIK_KLLNMM_SBP_AKL_TLF_TBL,EKIMLIK_KLLNMM_SBP_DGR,SON_KULLANIM_ETICARET,ETICARET_FIZIKSEL,WEBSTE_INT_MOBL_ABONE,WEBSTE_ELK_SU_ABONE,WEBSTE_UYGL_ULASIM,WEBSTE_UYGL_RZV_KONAKLAMA,WEBSTE_BILET,WEBSTE_KITAP_E_SESLI,WEBSTE_BLG_YZLM,WEBSTE_OYUN_OGE,WEBSTE_MUZIK_YAYIN,WEBSTE_FILM_SPOR,WEBSTE_DERGI_GAZETE,WEBSTE_OYUN_YAYIN,WEBSTE_SAGLK_UYGL,WEBSTE_UYGL_DIGER,WEBSTE_UYGLM_FZKSL_OZL_KSL,WEBSTE_UYGL_ULASIM_OZL_KSL,WEBSTE_UYGL_RZV_OZL_KSL,WEBSTE_HHN_HZMET_OZL_KSL,ETICARET_HRCM_KEZ_SONUCAY,WEBSTE_HRC_SRN_KULLANIM,WEBSTE_HRC_SRN_GARANTI,WEBSTE_HRC_SRN_TSLM_YAVAS,WEBSTE_HRC_SRN_YUK_MALYE,WEBSTE_HRC_SRN_YANLIS_MAL,WEBSTE_HRC_SRN_DOLANDRLKL,WEBSTE_HRC_SRN_SIKAYET,WEBSTE_HRC_SRN_YURTDISI,WEBSTE_HRC_SRN_DIGER,WEBSTE_HRC_SRN_YOK,ETICARET_SORUN_SAG_GUV,SOSMED_RKLM_ETIC_POLICE,SOSMED_RKLM_ETIC_BANKA,SOSMED_RKLM_ETIC_SENET,EYETENEK_BLGMOBIL_DOSYA_AKT,EYETENEK_BLGMOBIL_UYGLM_YUKLM,EYETENEK_BLGMOBIL_SISTEM_DEG,EYETENEK_YZLM_KLM_ISLEMCI,EYETENEK_YZLM_DOKUMN_OLSTRM,EYETENEK_YZLM_HZPRG_KULLNM,EYETENEK_YZLM_HZPRG_FORML,EYETENEK_YZLM_FOTO_VIDEO,EYETENEK_YZLM_KODYZM,EBECERI_ICERIK_SUPHE,EBECERI_ICERIK_KONTROL,EBECERI_ICERIK_KONTROL_BASKA,EBECERI_ICERIK_KONTROL_TART,EBECERI_ICERIK_KONTROL_DIGER,EBECERI_KNTRL_ETMEME_BILIYOR,EBECERI_KNTRL_ETMEME_EKSK_BLG,EBECERI_KNTRL_ETMEME_DIGER,INT_KBILGI_KORU_ACKOKUMA,INT_KBILGI_KORU_SINIR,INT_KBILGI_KORU_SINIR_SOSYAL,INT_KBILGI_KORU_IZINVRMEME,INT_KBILGI_KORU_WEBKNTRL,INT_KBILGI_KORU_WEB_TALP,INT_KBILGI_CEREZ_SNR,INT_KBILGI_RKLM_ENDS,INT_KBILGI_ETKNLIK_SNR,INT_HESAP_AC,INT_HESAP_SIL,INT_HESAP_SIL_SORUN,fert_faktor
0,10011,2025,3,1,65,1,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274