In [2]:
import pandas as pd

df = pd.read_excel(r"C:\Users\dilara\Desktop\Hane halkı bilişim tüik\hbtka_2025_fert.xlsx")

df.head()

,BULTEN_NO,REFERANS_YIL,GORUSME_YONTEM_FERT,CINSIYET,YAS,HHSORUMLU_YAKINLIK,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,CALISMAMA_NEDEN,...,INT_KBILGI_KORU_IZINVRMEME,INT_KBILGI_KORU_WEBKNTRL,INT_KBILGI_KORU_WEB_TALP,INT_KBILGI_CEREZ_SNR,INT_KBILGI_RKLM_ENDS,INT_KBILGI_ETKNLIK_SNR,INT_HESAP_AC,INT_HESAP_SIL,INT_HESAP_SIL_SORUN,fert_faktor
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274

In [3]:
df = pd.DataFrame(df)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25493 entries, 0 to 25492
Columns: 157 entries, BULTEN_NO to fert_faktor
dtypes: float64(143), int64(12), str(2)
memory usage: 30.5 MB

In [5]:
df["BULTEN_NO"].value_counts()

BULTEN_NO
18336     10
20863      8
23969      8
10938      7
13105      7
          ..
236010     1
237310     1
238510     1
240610     1
240810     1
Name: count, Length: 11924, dtype: int64

In [6]:
df.rename(columns={"BULTEN_NO": "bülten no"}, inplace=True)

In [7]:
df["REFERANS_YIL"].value_counts()

REFERANS_YIL
2025    25493
Name: count, dtype: int64

In [8]:
df.rename(columns={"REFERANS_YIL": "referans yıl"}, inplace=True)

In [9]:
df.head()

,bülten no,referans yıl,GORUSME_YONTEM_FERT,CINSIYET,YAS,HHSORUMLU_YAKINLIK,OKUL_BITEN,OKUMA_YAZMA,CALISMA_DURUM,CALISMAMA_NEDEN,...,INT_KBILGI_KORU_IZINVRMEME,INT_KBILGI_KORU_WEBKNTRL,INT_KBILGI_KORU_WEB_TALP,INT_KBILGI_CEREZ_SNR,INT_KBILGI_RKLM_ENDS,INT_KBILGI_ETKNLIK_SNR,INT_HESAP_AC,INT_HESAP_SIL,INT_HESAP_SIL_SORUN,fert_faktor
0,10011,2025,3,1,65,1,512,NaN,3,5.0,...,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,...,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,...,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,...,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,...,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274

In [10]:
df["GORUSME_YONTEM_FERT"].value_counts()

GORUSME_YONTEM_FERT
3    18385
1     7108
Name: count, dtype: int64

In [12]:
df.rename(columns={"GORUSME_YONTEM_FERT": "fert no"}, inplace=True)

In [14]:
df.rename(columns={"CINSIYET": "cinsiyet"}, inplace=True)

In [18]:
df.rename(columns={"YAS": "yaş"}, inplace=True)

In [19]:
df.rename(columns={"HHSORUMLU_YAKINLIK": "yakınlık durumu"}, inplace=True)

In [22]:
df.rename(columns={"OKUL_BITEN": "eğitim"}, inplace=True)

In [24]:
df.rename(columns={"OKUMA_YAZMA": "okuma yazma durumu"}, inplace=True)

In [33]:
df.rename(columns={"CALISMA_DURUM": "çalışma durumu"}, inplace=True)

In [35]:
df.rename(columns={"CALISMAMA_NEDEN": "çalışmama nedeni"}, inplace=True)

In [37]:
df.rename(columns={"ISTEKI_DURUM": "işteki durumu"}, inplace=True)

In [45]:
df.rename(columns={"ISCO08": "uluslararası meslek"}, inplace=True)

In [47]:
df.rename(columns={"DOGUM_YER": "doğduğu ülke"}, inplace=True)

In [48]:
df.rename(columns={"DOGUM_YER_ULKE_KOD": "doğduğu ülke kodu"}, inplace=True)

In [50]:
df.rename(columns={"UYRUK": "uyruk"}, inplace=True)

In [52]:
df.rename(columns={"UYRUK_ULKE_KOD": "uyruk ülke kodu"}, inplace=True)

In [53]:
df.rename(columns={"KULLANIM_CEP": "cep telefonu kullanımı"}, inplace=True)

In [55]:
df.rename(columns={"CEP_SAHIP": "cep telefonuna sahip"}, inplace=True)

In [57]:
df.rename(columns={"SON_KULLANIM_INTERNET": "en son internet ne zaman kullanıldı"}, inplace=True)

In [60]:
df.rename(columns={"KULLANIM_SIKLIK_INTERNET": "internet kullanım sıklığı"}, inplace=True)

In [64]:
df.rename(columns={"FERT_INT_MASAUSTU": "masaüstü kullanımı"}, inplace=True)

In [65]:
df.rename(columns={"FERT_INT_DIZUSTU": "dizüstü kullanımı"}, inplace=True)

In [66]:
df.rename(columns={"FERT_INT_TABLET": "tablet kullanımı"}, inplace=True)

In [68]:
df.rename(columns={"FERT_INT_TEL_CEP": "cep telefonu kullanımı"}, inplace=True)

In [70]:
df.rename(columns={"FERT_INT_DGR_CIHAZ": "diğer cihaz kullanımı"}, inplace=True)

In [77]:
df.rename(columns={"INT_FAAL_EPOSTA": "eposta kullanımı"}, inplace=True)

In [79]:
df.rename(columns={"INT_FAAL_TELEFON": "internet araması"}, inplace=True)

In [81]:
df.rename(columns={"INT_FAAL_SOSYAL_GRKATILIM": "sosyal medya kullanımı"}, inplace=True)

In [85]:
df.rename(columns={"INT_FAAL_MESAJ": "sosyal medyada mesajlaşma"}, inplace=True)

In [87]:
df.rename(columns={"INT_FAAL_ONLINE_HABER": "online haber okuma"}, inplace=True)

In [88]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM": "sağlık bilgisi arama"}, inplace=True)

In [89]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM_F": "fiziksel sağlık bilgisi arama"}, inplace=True)

In [90]:
df.rename(columns={"INT_FAAL_SAGLIK_BILGI_ARM_R": "ruhsal sağlık bilgisi arama"}, inplace=True)

In [91]:
df.rename(columns={"INT_FAAL_MALHIZ_BILGI": "ürün hizmet arama"}, inplace=True)

In [92]:
df.rename(columns={"INT_FAAL_MALHIZ_BILGI_GVNLK": "ürün güvenliği hakkında arama"}, inplace=True)

In [93]:
df.rename(columns={"INT_FAAL_WEBSITE_PAYLASIM": "websitesinde içerik paylaşma"}, inplace=True)

In [96]:
df.rename(columns={"INT_FAAL_OYL_KTLM": "internetten oy katılım"}, inplace=True)

In [98]:
df.rename(columns={"INT_FAAL_ISARAMA": "internetten iş arama"}, inplace=True)

In [101]:
df.rename(columns={"INT_FAAL_MALHIZMET_SATIS": ""}, inplace=True)

In [99]:
df.rename(columns={"INT_FAAL_BANKA_ISLEM": "internetten satış"}, inplace=True)

In [105]:
df.rename(columns={"YAPAYZEKA_KULLAN": "yapay zeka kullanımı"}, inplace=True)

In [107]:
df.rename(columns={"YAPAYZEKA_AMAC_OZEL": "yapay zeka özel amaç kullanımı"}, inplace=True)

In [109]:
df.rename(columns={"YAPAYZEKA_AMAC_IS": "yapay zeka iş için kullanımı"}, inplace=True)

In [111]:
df.rename(columns={"YAPAYZEKA_AMAC_EGT_FRML": "yapay zeka eğitim için kullanımı"}, inplace=True)

In [113]:
df.rename(columns={"YAPAYZEKA_KULLANMAMA_NEDEN": "yapay zeka kullanmama nedeni"}, inplace=True)

In [115]:
df.rename(columns={"INT_FAAL_EGT_KURS": "online kurs"}, inplace=True)

In [117]:
df.rename(columns={"INT_FAAL_EGT_OGRN_MTRYL": "online eğitim materyal"}, inplace=True)

In [119]:
df.rename(columns={"INT_FAAL_EGT_WEB": "online eğitim iletişim"}, inplace=True)

In [121]:
df.rename(columns={"KULLAN_WHATSAPP": "whatsapp kullanımı"}, inplace=True)

In [123]:
df.rename(columns={"KULLAN_INSTAGRAM": "instagram kullanımı"}, inplace=True)

In [126]:
df.rename(columns={"KULLAN_YOUTUBE": "youtube kullanımı"}, inplace=True)

In [127]:
df.rename(columns={"KULLAN_FACEBOOK": "facebook kullanımı"}, inplace=True)

In [128]:
df.rename(columns={"KULLAN_TWITTER": "twitter kullanımı"}, inplace=True)

In [129]:
df.rename(columns={"KULLAN_TELEGRAM": "telegram kullanımı"}, inplace=True)

In [131]:
df.rename(columns={"KULLAN_TIKTOK": "tiktok kullanımı"}, inplace=True)

In [132]:
df.rename(columns={"KULLAN_SNAPCHAT": "snapchat kullanımı"}, inplace=True)

In [134]:
df.rename(columns={"KULLAN_BIP": "bip kullanımı"}, inplace=True)

In [135]:
df.rename(columns={"KULLAN_DIGER": "diğer mobil uygulama kullanımları"}, inplace=True)

In [138]:
df.rename(columns={"EDEVLET_KSL_BILGI_ERISME": "edevlet resmi işlem"}, inplace=True)

In [139]:
df.rename(columns={"EDEVLET_KAMU_BILGI_ERISME": "edevlet kamu bilgi"}, inplace=True)

In [140]:
df.rename(columns={"EDEVLET_BILGI_EDINME": "edevlet hakkında bilgi"}, inplace=True)

In [141]:
df.rename(columns={"EDEVLET_HICBIRI": "edevlette hiçbir sey yapmadı"}, inplace=True)

In [143]:
df.rename(columns={"EDEVLET_FORM_INDIRME": "edevlet form işlemleri"}, inplace=True)

In [144]:
df.rename(columns={"EDEVLET_RANDEVU_REZRVSYN": "edevletten randevu alma"}, inplace=True)

In [145]:
df.rename(columns={"EDEVLET_HESAP_BLG_ALMA": "edevletten bilgi alma"}, inplace=True)

In [146]:
df.rename(columns={"EDEVLET_KSL_VERGI_ONAY": "edevlet vergi işlem"}, inplace=True)

In [147]:
df.rename(columns={"EDEVLET_TALEP_BELGE_SRTFKA": "edevlet belge talep"}, inplace=True)

In [148]:
df.rename(columns={"EDEVLET_TALEP_YARDIM_HAK": "edevlet yardım talep"}, inplace=True)

In [149]:
df.rename(columns={"EDEVLET_TALEP_DIGER": "edevlet diğer talepler"}, inplace=True)

In [151]:
df.rename(columns={"EDEVLET_TALEP_HIC_IHTIYACYOK": "edevletten talepe ihtiyaç yok"}, inplace=True)

In [156]:
df.rename(columns={"EDEVLET_TALEP_HIC_EKSKBILG": "edevlet kullanımı bilgi eksiği"}, inplace=True)

In [158]:
df.rename(columns={"EDEVLET_TALEP_HIC_GUVENSIZ": "edevlet güven sorunu"}, inplace=True)

In [160]:
df.rename(columns={"EDEVLET_TALEP_HIC_EKIMLIKYOK": "edevlet dijital kimlik yok"}, inplace=True)

In [162]:
df.rename(columns={"EDEVLET_TALEP_HIC_BASKASI": "edevlet işlemlerini başkası yapıyor"}, inplace=True)

In [164]:
df.rename(columns={"EDEVLET_TALEP_HIC_DIGER": "edevlet kullanım diğer"}, inplace=True)

In [166]:
df.rename(columns={"EDEVLET_SORUN_ZOR": "edevlet kullanımı zor"}, inplace=True)

In [167]:
df.rename(columns={"EDEVLET_SORUN_TEKNIK": "edevlet kullanırken teknik sorunlar"}, inplace=True)

In [168]:
df.rename(columns={"EDEVLET_SORUN_E_IMZA_KIMLIK": "edevlet eimza sorunu"}, inplace=True)

In [173]:
df.rename(columns={"EDEVLET_SORUN_ODEME": "edevlet ödeme sorunu"}, inplace=True)

In [174]:
df.rename(columns={"EDEVLET_SORUN_MOBIL_ERISIM": "edevlet mobil erişim sorunu"}, inplace=True)

In [175]:
df.rename(columns={"EDEVLET_SORUN_DIGER": "edevlette diğer sorunlar"}, inplace=True)

In [176]:
df.rename(columns={"EDEVLET_SORUN_HIC": "edevlette sorun yok"}, inplace=True)

In [178]:
df.rename(columns={"EKIMLIK_ERSM_OZEL_AMAC": "ekimliği özel amaç için kullanma"}, inplace=True)

In [180]:
df.rename(columns={"EKIMLIK_KAMU_HZMT": "ekimliği kamu hizmeti için kullanma"}, inplace=True)

In [181]:
df.rename(columns={"EKIMLIK_OZEL_HZMT": "ekimliği özel hizmet için kullanma"}, inplace=True)

In [183]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_HBR_DGL": "ekimlikten haberi yok"}, inplace=True)

In [185]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_YOK": "ekimlik yok"}, inplace=True)

In [188]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_GRKMD": "ekimlik var ama ihtiyaç olmadı"}, inplace=True)

In [189]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_GVNSZ": "ekimlik var ama kullanımı güvenli değil"}, inplace=True)

In [190]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_TKNK_SRN": "ekimliği teknik sorundan kullanamama"}, inplace=True)

In [195]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_AKL_TLF_TBL": "ekimlik mobil erişim yok"}, inplace=True)

In [197]:
df.rename(columns={"EKIMLIK_KLLNMM_SBP_DGR": "ekimlik var ama baska sebeplerle kullanmıyorum"}, inplace=True)

In [200]:
df.rename(columns={"SON_KULLANIM_ETICARET": "eticaret kullanımı"}, inplace=True)

In [207]:
df.rename(columns={"ETICARET_FIZIKSEL": "eticaretten alınan fiziksel mal"}, inplace=True)

In [208]:
df.rename(columns={"WEBSTE_INT_MOBL_ABONE": "internet bağlantı aboneliği"}, inplace=True)

In [209]:
df.rename(columns={"WEBSTE_ELK_SU_ABONE": "elektrik su doğal gaz vb hizmet aboneliği"}, inplace=True)

In [211]:
df.rename(columns={"WEBSTE_UYGL_ULASIM": "online ulaşım hizmeti"}, inplace=True)

In [212]:
df.rename(columns={"WEBSTE_UYGL_RZV_KONAKLAMA": "online konaklama hizmeti"}, inplace=True)

In [214]:
df.rename(columns={"WEBSTE_BILET": "online etkinlik biletleri"}, inplace=True)

In [215]:
df.rename(columns={"WEBSTE_KITAP_E_SESLI": "ekitap sesli kitap"}, inplace=True)

In [218]:
df.rename(columns={"WEBSTE_BLG_YZLM": "yazılım indirme sürüm yükseltme"}, inplace=True)

In [219]:
df.rename(columns={"WEBSTE_OYUN_OGE": "oyun indirme sürüm yükseltme"}, inplace=True)

In [223]:
df.rename(columns={"WEBSTE_MUZIK_YAYIN": "online müzik dinleme platformu"}, inplace=True)

In [222]:
df.rename(columns={"WEBSTE_FILM_SPOR": "online film/dizi/video platformu"}, inplace=True)

In [225]:
df.rename(columns={"WEBSTE_DERGI_GAZETE": "online dergi gazete"}, inplace=True)

In [226]:
df.rename(columns={"WEBSTE_OYUN_YAYIN": "oyun yayın platformu"}, inplace=True)

In [228]:
df.rename(columns={"WEBSTE_SAGLK_UYGL": "sağlık/sağlıklı yaşam uygulamaları"}, inplace=True)

In [229]:
df.rename(columns={"WEBSTE_UYGL_DIGER": "diğer mobil uygulamalar"}, inplace=True)

In [232]:
df.rename(columns={"WEBSTE_UYGLM_FZKSL_OZL_KSL": "online c2c alışveriş"}, inplace=True)

In [234]:
df.rename(columns={"WEBSTE_UYGL_ULASIM_OZL_KSL": "online ulaşım paylaşımı"}, inplace=True)

In [239]:
df.rename(columns={"WEBSTE_UYGL_RZV_OZL_KSL": "online p2p konaklama"}, inplace=True)

In [241]:
df.rename(columns={"WEBSTE_HHN_HZMET_OZL_KSL": "online ev hizmetleri"}, inplace=True)

In [244]:
df.rename(columns={"ETICARET_HRCM_KEZ_SONUCAY": "eticaret alışveriş sıklık"}, inplace=True)

In [245]:
df.rename(columns={"WEBSTE_HRC_SRN_KULLANIM": "web kullanım zorluğu"}, inplace=True)

In [246]:
df.rename(columns={"WEBSTE_HRC_SRN_GARANTI": "web garanti bilgi sorun"}, inplace=True)

In [248]:
df.rename(columns={"WEBSTE_HRC_SRN_TSLM_YAVAS": "webde yapılan satın almanın teslimat gecikmesi sorunu"}, inplace=True)

In [250]:
df.rename(columns={"WEBSTE_HRC_SRN_YUK_MALYE": "webde yapılan satın almanın beklenenden yüksek maliyet"}, inplace=True)

In [252]:
df.rename(columns={"WEBSTE_HRC_SRN_YANLIS_MAL": "webde yapılan satın alınanın yanlış/hasarlı olması"}, inplace=True)

In [254]:
df.rename(columns={"WEBSTE_HRC_SRN_DOLANDRLKL": "webde yapılan satın almanın dolandırıcılık sorunu"}, inplace=True)

In [256]:
df.rename(columns={"WEBSTE_HRC_SRN_SIKAYET": "webde yapılan satın almaların şikayet iade tazminat sorunu"}, inplace=True)

In [262]:
df.rename(columns={"WEBSTE_HRC_SRN_YURTDISI": "yurt dışı web sitelerinde alışveriş engeli "}, inplace=True)

In [263]:
df.rename(columns={"WEBSTE_HRC_SRN_DIGER": "web alısverişlerindeki diğer sorunlar "}, inplace=True)

In [264]:
df.rename(columns={"WEBSTE_HRC_SRN_YOK": "web alışverişlerinde sorun yok"}, inplace=True)

In [267]:
df.rename(columns={"ETICARET_SORUN_SAG_GUV": "eticaret sağlık güven sorunu"}, inplace=True)

In [268]:
df.rename(columns={"SOSMED_RKLM_ETIC_POLICE": "online sigorta işlemleri"}, inplace=True)

In [271]:
df.rename(columns={"SOSMED_RKLM_ETIC_BANKA": "online banka işlemleri"}, inplace=True)

In [272]:
df.rename(columns={"SOSMED_RKLM_ETIC_SENET": "online yatırım işlemleri"}, inplace=True)

In [273]:
df.rename(columns={"EYETENEK_BLGMOBIL_DOSYA_AKT": "dijital beceri dosya transfer"}, inplace=True)

In [274]:
df.rename(columns={"EYETENEK_BLGMOBIL_UYGLM_YUKLM": "dijital beceri uygulama kurulum"}, inplace=True)

In [275]:
df.rename(columns={"EYETENEK_BLGMOBIL_SISTEM_DEG": "dijital beceri ayar değiştirme"}, inplace=True)

In [276]:
df.rename(columns={"EYETENEK_YZLM_KLM_ISLEMCI": "dijital beceri ofis yazılımı kullanma"}, inplace=True)

In [277]:
df.rename(columns={"EYETENEK_YZLM_DOKUMN_OLSTRM": "dijital beceri doküman oluşturma"}, inplace=True)

In [278]:
df.rename(columns={"EYETENEK_YZLM_HZPRG_KULLNM": "dijital beceri tablolama yazılımı kullanma"}, inplace=True)

In [279]:
df.rename(columns={"EYETENEK_YZLM_HZPRG_FORML": "dijital beceri tablolama ileri yazılım kullanma"}, inplace=True)

In [280]:
df.rename(columns={"EYETENEK_YZLM_FOTO_VIDEO": "dijital beceri foto video düzenleme"}, inplace=True)

In [281]:
df.rename(columns={"EYETENEK_YZLM_KODYZM": "dijital beceri kod yazma"}, inplace=True)

In [282]:
df.rename(columns={"EBECERI_ICERIK_SUPHE": "dijital beceri şüpheli içerikle karşılaşma"}, inplace=True)

In [283]:
df.rename(columns={"EBECERI_ICERIK_KONTROL": "dijital beceri şüpheli içerik kontrol etme"}, inplace=True)

In [285]:
df.rename(columns={"EBECERI_ICERIK_KONTROL_BASKA": "dijital beceri bilgi kaynağı kontrolü"}, inplace=True)

In [286]:
df.rename(columns={"EBECERI_ICERIK_KONTROL_TART": "dijital beceri içerik tartışmaya katılım"}, inplace=True)

In [290]:
df.rename(columns={"EBECERI_ICERIK_KONTROL_DIGER": "dijital beceri içerik offline tartışma"}, inplace=True)

In [291]:
df.rename(columns={"EBECERI_KNTRL_ETMEME_BILIYOR": "dijital beceri güvenilmez bilgi farkındalığı"}, inplace=True)

In [292]:
df.rename(columns={"EBECERI_KNTRL_ETMEME_EKSK_BLG": "dijital beceri bilgi beceri eksikliği"}, inplace=True)

In [293]:
df.rename(columns={"EBECERI_KNTRL_ETMEME_DIGER": "dijital beceri bilgiyi kontrol etmeme diğer"}, inplace=True)

In [296]:
df.rename(columns={"INT_KBILGI_KORU_ACKOKUMA": "kvkk gizlilik politikası okuması"}, inplace=True)

In [297]:
df.rename(columns={"INT_KBILGI_KORU_SINIR": "kvkk konum erişimini kısıtlama"}, inplace=True)

In [300]:
df.rename(columns={"INT_KBILGI_KORU_SINIR_SOSYAL": "kvkk sosyal medya gizlilik"}, inplace=True)

In [301]:
df.rename(columns={"INT_KBILGI_KORU_IZINVRMEME": "kvkk veri paylaşım reddetme"}, inplace=True)

In [302]:
df.rename(columns={"INT_KBILGI_KORU_WEBKNTRL": "kvkk web güvenlik kontrolü"}, inplace=True)

In [303]:
df.rename(columns={"INT_KBILGI_KORU_WEB_TALP": "kvkk veri güncelleme silme talep"}, inplace=True)

In [304]:
df.rename(columns={"INT_KBILGI_CEREZ_SNR": "kvkk çerez yönetimi"}, inplace=True)

In [307]:
df.rename(columns={"INT_KBILGI_RKLM_ENDS": "kvkk reklam takip endişesi"}, inplace=True)

In [308]:
df.rename(columns={"INT_KBILGI_ETKNLIK_SNR": "kvkk izleme engelleme yazılım kullanma"}, inplace=True)

In [310]:
df.rename(columns={"INT_HESAP_AC": "online hesap açma"}, inplace=True)

In [311]:
df.rename(columns={"INT_HESAP_SIL": "online hesap silme"}, inplace=True)

In [313]:
df.rename(columns={"INT_HESAP_SIL_SORUN": "online hesap silerken sorun olması"}, inplace=True)

In [314]:
df.rename(columns={"fert_faktor": "fert ağırlık katsayısı"}, inplace=True)

In [315]:
cols = list(df.columns)
len(cols), cols[139:157], cols[139:157]

(157,
 ['dijital beceri içerik tartışmaya katılım',
  'dijital beceri içerik offline tartışma',
  'dijital beceri güvenilmez bilgi farkındalığı',
  'dijital beceri bilgi beceri eksikliği',
  'dijital beceri bilgiyi kontrol etmeme diğer',
  'kvkk gizlilik politikası okuması',
  'kvkk konum erişimini kısıtlama',
  'kvkk sosyal medya gizlilik',
  'kvkk veri paylaşım reddetme',
  'kvkk web güvenlik kontrolü',
  'kvkk veri güncelleme silme talep',
  'kvkk çerez yönetimi',
  'kvkk reklam takip endişesi',
  'kvkk izleme engelleme yazılım kullanma',
  'online hesap açma',
  'online hesap silme',
  'online hesap silerken sorun olması',
  'fert ağırlık katsayısı'],
 ['dijital beceri içerik tartışmaya katılım',
  'dijital beceri içerik offline tartışma',
  'dijital beceri güvenilmez bilgi farkındalığı',
  'dijital beceri bilgi beceri eksikliği',
  'dijital beceri bilgiyi kontrol etmeme diğer',
  'kvkk gizlilik politikası okuması',
  'kvkk konum erişimini kısıtlama',
  'kvkk sosyal medya gizlilik',
  'kvkk veri paylaşım reddetme',
  'kvkk web güvenlik kontrolü',
  'kvkk veri güncelleme silme talep',
  'kvkk çerez yönetimi',
  'kvkk reklam takip endişesi',
  'kvkk izleme engelleme yazılım kullanma',
  'online hesap açma',
  'online hesap silme',
  'online hesap silerken sorun olması',
  'fert ağırlık katsayısı'])

In [316]:
df.head()

,bülten no,referans yıl,fert no,cinsiyet,yaş,yakınlık durumu,eğitim,okuma yazma durumu,çalışma durumu,çalışmama nedeni,işteki durumu,uluslararası meslek,doğduğu ülke,doğduğu ülke kodu,uyruk,uyruk ülke kodu,cep telefonu kullanımı,cep telefonuna sahip,en son internet ne zaman kullanıldı,internet kullanım sıklığı,masaüstü kullanım,dizüstü kullanım,tablet kullanımı,cep telefonu kullanımı,diğer cihaz kullanımı,eposta kullanımı,internet araması,sosyal medya kullanımı,sosyal medyada mesajlaşma,online haber okuma,sağlık bilgisi arama,fiziksel sağlık bilgisi arama,ruhsal sağlık bilgisi arama,ürün hizmet arama,ürün güvenliği hakkında arama,websitesinde içerik paylaşma,online oy katılım,internet iş arama,,internetten satış,yapay zeka kullanımı,yapay zeka özel amaç kullanımı,yapay zeka iş için kullanımı,yapay zeka eğitim için kullanımı,yapay zeka kullanmama nedeni,online kurs,online eğitim materyal,online eğitim iletişim,whatsapp kullanımı,instagram kullanımı,youtube kullanımı,facebook kullanımı,twitter kullanımı,telegram kullanımı,tiktok kullanımı,snapchat kullanımı,bip kullanımı,diğer mobil uygulama kullanımları,edevlet resmi işlem,edevlet kamu bilgi,edevlet hakkında bilgi,edevlette hiçbir sey yapmadı,edevlet form işlemleri,edevletten randevu alma,edevletten bilgi alma,edevlet vergi işlem,edevlet belge talep,edevlet yardım talep,edevlet diğer talepler,edevletten talepe ihtiyaç yok,edevlet kullanımı bilgi eksiği,edevlet güven sorunu,edevlet dijital kimlik yok,edevlet işlemlerini başkası yapıyor,edevlet kullanım diğer,edevlet kullanımı zor,edevlet kullanırken teknik sorunlar,edevlet eimza sorunu,edevlet ödeme sorunu,edevlet mobil erişim sorunu,edevlette diğer sorunlar,edevlette sorun yok,ekimliği özel amaç için kullanma,ekimliği kamu hizmeti için kullanma,ekimliği özel hizmet için kullanma,ekimlikten haberi yok,ekimlik yok,ekimliğe ihtiyaç olmadı,ekimlik var ama kullanımı güvenli değil,ekimliği teknik sorundan kullanamama,ekimlik mobil erişim yok,ekimlik var ama baska sebeplerle kullanmıyorum,eticaret kullanımı,eticaretten alınan fiziksel mal,internet bağlantı aboneliği,elektrik su doğal gaz vb hizmet aboneliği,online ulaşım hizmeti,online konaklama hizmeti,online etkinlik biletleri,ekitap sesli kitap,yazılım indirme sürüm yükseltme,oyun indirme sürüm yükseltme,online müzik dinleme,online film/dizi/video platformu,online dergi gazete,oyun yayın platformu,sağlık/sağlıklı yaşam uygulamaları,diğer mobil uygulamalar,online c2c alışveriş,online ulaşım paylaşımı,online p2p konaklama,online ev hizmetleri,eticaret alışveriş sıklık,web kullanım zorluğu,web garanti bilgi sorun,webde yapılan satın almanın teslimat gecikmesi sorunu,webde yapılan satın almanın beklenenden yüksek maliyet,webde yapılan satın alınanın yanlış/hasarlı olması,webde yapılan satın almanın dolandırıcılık sorunu,webde yapılan satın almaların şikayet iade tazminat sorunu,yurt dışı web sitelerinde alışveriş engeli,web alısverişlerindeki diğer sorunlar,web alışverişlerinde sorun yok,eticaret sağlık güven sorunu,online sigorta işlemleri,online banka işlem,online yatırım işlemleri,dijital beceri dosya transfer,dijital beceri uygulama kurulum,dijital beceri ayar değiştirme,dijital beceri ofis yazılımı kullanma,dijital beceri doküman oluşturma,dijital beceri tablolama yazılımı kullanma,dijital beceri tablolama ileri yazılım kullanma,dijital beceri foto video düzenleme,dijital beceri kod yazma,dijital beceri şüpheli içerikle karşılaşma,dijital beceri şüpheli içerik kontrol etme,dijital beceri bilgi kaynağı kontrolü,dijital beceri içerik tartışmaya katılım,dijital beceri içerik offline tartışma,dijital beceri güvenilmez bilgi farkındalığı,dijital beceri bilgi beceri eksikliği,dijital beceri bilgiyi kontrol etmeme diğer,kvkk gizlilik politikası okuması,kvkk konum erişimini kısıtlama,kvkk sosyal medya gizlilik,kvkk veri paylaşım reddetme,kvkk web güvenlik kontrolü,kvkk veri güncelleme silme talep,kvkk çerez yönetimi,kvkk reklam takip endişesi,kvkk izleme engelleme yazılım kullanma,online hesap açma,online hesap silme,online hesap silerken sorun olması,fert ağırlık katsayısı
0,10011,2025,3,1,65,1,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
1,10011,2025,3,2,60,2,512,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1131.0,2.0,1.0,2.0,NaN,3045.660009
2,10012,2025,3,1,49,1,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
3,10012,2025,3,2,45,2,512,NaN,1,NaN,1.0,2330.0,1,NaN,1,NaN,1,1.0,1,16.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1130.0,2.0,1.0,2.0,NaN,2295.674589
4,10013,2025,3,1,70,1,4,NaN,3,5.0,NaN,NaN,1,NaN,1,NaN,1,1.0,1,16.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1222.0,2.0,2.0,NaN,NaN,3813.920274